return function(b)
 b.task("SUPER + Return","Open terminal","app terminal")
 b.task("SUPER + SHIFT + Return","Open browser","app browser")
 b.task("SUPER + SHIFT + F","Open files","app files")
 b.task("SUPER + ALT + SHIFT + F","Open files-cwd","app files-cwd")
 b.task("SUPER + SHIFT + B","Open browser","app browser")
 b.task("SUPER + SHIFT + ALT + B","Open browser-private","app browser-private")
 b.task("SUPER + SHIFT + N","Open editor","app editor")
 b.task("SUPER + ALT + Return","Open tmux","app tmux")
 b.task("SUPER + CTRL + Return","Open herdr","app herdr")
 b.task("SUPER + SHIFT + M","Open spotify","app spotify")
 b.task("SUPER + SHIFT + ALT + M","Open cliamp","app cliamp")
 b.task("SUPER + SHIFT + D","Open docker","app docker")
 b.task("SUPER + SHIFT + G","Open signal","app signal")
 b.task("SUPER + SHIFT + O","Open obsidian","app obsidian")
 b.task("SUPER + SHIFT + W","Open omawrite","app omawrite")
 b.task("SUPER + SHIFT + slash","Open passwords","app passwords")
 b.task("SUPER + SHIFT + A","Open chatgpt","app chatgpt")
 b.task("SUPER + SHIFT + ALT + A","Open grok","app grok")
 b.task("SUPER + SHIFT + C","Open calendar","app calendar")
 b.task("SUPER + SHIFT + E","Open email","app email")
 b.task("SUPER + SHIFT + ALT + E","Open email-new","app email-new")
 b.task("SUPER + SHIFT + Y","Open youtube","app youtube")
 b.task("SUPER + SHIFT + ALT + G","Open whatsapp","app whatsapp")
 b.task("SUPER + SHIFT + CTRL + G","Open messages","app messages")
 b.task("SUPER + SHIFT + P","Open photos","app photos")
 b.task("SUPER + SHIFT + S","Open maps","app maps")
 b.task("SUPER + SHIFT + X","Open x","app x")
 b.task("SUPER + SHIFT + ALT + X","Open x-post","app x-post")
end
