# Titan's original Limine operations. Sourced only by scripts/titan-boot.
# Refresh is confined to fresh UEFI QEMU installs, including the install chroot.
titan_boot_marker='# Generated by Titan; edit /etc/titan/limine.conf for menu appearance.'

titan_boot_fail() { echo "titan boot: $*" >&2; return 1; }

titan_boot_path() {
 local candidate=$1
 [[ ! -e $candidate || -f $candidate ]] || { titan_boot_fail "Boot output is not a regular file: $candidate"; return 1; }
 while [[ $candidate != / ]]; do
  [[ ! -L $candidate ]] || { titan_boot_fail "Refusing linked boot path: $candidate"; return 1; }
  candidate=$(dirname -- "$candidate")
 done
}

titan_boot_render() {
 local uuid=$1 esp=$2 header=$3 kernel name initramfs fallback found=0
 [[ $uuid =~ ^[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$ ]] || { titan_boot_fail 'Invalid Btrfs root UUID'; return 1; }
 [[ -f $header && ! -L $header ]] || { titan_boot_fail 'Missing or linked Limine appearance configuration'; return 1; }
 printf '%s\n' "$titan_boot_marker" || return
 cat -- "$header" || return
 printf '\n' || return
 for kernel in "$esp"/vmlinuz-*; do
  [[ -e $kernel || -L $kernel ]] || continue
  name=${kernel##*/vmlinuz-}
  [[ $name =~ ^linux(-(lts|zen|hardened))?$ ]] || { titan_boot_fail "Unsupported kernel image: ${kernel##*/}"; return 1; }
  initramfs=$esp/initramfs-$name.img
  [[ -f $kernel && ! -L $kernel && -f $initramfs && ! -L $initramfs ]] || { titan_boot_fail "Missing or linked initramfs for $name; rebuild before refreshing"; return 1; }
  found=$((found+1))
  printf '\n/Titan (%s)\n    protocol: linux\n    path: boot():/%s\n    module_path: boot():/%s\n    cmdline: root=UUID=%s rw rootflags=subvol=@ quiet splash plymouth.ignore-serial-consoles\n' "$name" "${kernel##*/}" "${initramfs##*/}" "$uuid" || return
  fallback=$esp/initramfs-$name-fallback.img
  [[ ! -L $fallback ]] || { titan_boot_fail 'Fallback initramfs must not be a symlink'; return 1; }
  if [[ -f $fallback ]]; then
   printf '\n/Titan (%s fallback)\n    protocol: linux\n    path: boot():/%s\n    module_path: boot():/%s\n    cmdline: root=UUID=%s rw rootflags=subvol=@ quiet splash plymouth.ignore-serial-consoles\n' "$name" "${kernel##*/}" "${fallback##*/}" "$uuid" || return
  fi
 done
 ((found)) || { titan_boot_fail 'No supported kernel/initramfs pairs on /boot'; return 1; }
 titan_snapshot_render "$uuid" "$esp"
}

titan_boot_status() {
 local loader=unmanaged plan=/etc/titan/install-plan.json config=false binary=false snapshot=false preview=false file
 if [[ -e $plan || -L $plan ]]; then
  [[ -f $plan && ! -L $plan ]] || { titan_boot_fail 'Installer plan must be a regular file'; return 1; }
  command -v jq >/dev/null || { titan_boot_fail "Managed boot status requires jq (installed by the Limine recipe)"; return 1; }
  loader=$(jq -er '.bootloader // "systemd-boot"' "$plan")
 fi
 [[ ! -f /boot/limine.conf ]] || config=true
 [[ ! -f /boot/EFI/BOOT/BOOTX64.EFI ]] || binary=true
 case $loader in unmanaged|systemd-boot|limine) ;; *) titan_boot_fail 'Invalid bootloader in installer plan'; return 1 ;; esac
 if [[ $loader == limine ]]; then
  preview=true
  for file in /boot/titan/snapshots/*/manifest.json; do
   [[ ! -f $file || -L $file ]] || snapshot=true
  done
 fi
 printf '{"schema":1,"bootloader":"%s","experimental":true,"refresh_scope":"fresh Titan Limine QEMU installations only","configuration_exists":%s,"efi_exists":%s,"snapshot_boot":%s,"snapshot_preview_supported":%s,"snapshot_restore_supported":false}\n' "$loader" "$config" "$binary" "$snapshot" "$preview"
}

titan_boot_guard() {
 ((EUID == 0)) || { titan_boot_fail 'Refresh requires root; run sudo titan boot refresh in the installed VM'; return 1; }
 case $(systemd-detect-virt --vm) in qemu|kvm) ;; *) titan_boot_fail 'Limine refresh is experimental and confined to QEMU VMs'; return 1 ;; esac
 [[ -d /sys/firmware/efi ]] || { titan_boot_fail 'Limine refresh requires UEFI'; return 1; }
 local plan=/etc/titan/install-plan.json uuid
 [[ -f $plan && ! -L $plan ]] || { titan_boot_fail 'Missing or linked Titan installer plan'; return 1; }
 jq -e '.bootloader == "limine" and .apply_scope == "QEMU live VM only"' "$plan" >/dev/null || { titan_boot_fail 'Refresh requires a fresh Titan Limine installer plan'; return 1; }
 uuid=$(jq -er '.root_uuid' "$plan")
 [[ $(findmnt -nro FSTYPE --mountpoint /) == btrfs && $(findmnt -nro FSROOT --mountpoint /) == /@ && $(findmnt -nro UUID --mountpoint /) == "$uuid" ]] || { titan_boot_fail 'The running Btrfs root does not match the installer plan'; return 1; }
 [[ $(findmnt -nro FSTYPE --mountpoint /boot) == vfat ]] || { titan_boot_fail '/boot must be a mounted FAT EFI partition'; return 1; }
 titan_boot_uuid=$uuid
}

titan_boot_refresh() {
 titan_boot_guard || return
 local uuid=$titan_boot_uuid config=/boot/limine.conf binary=/boot/EFI/BOOT/BOOTX64.EFI path stage source=/usr/share/limine/BOOTX64.EFI
 [[ -f $source && ! -L $source ]] || { titan_boot_fail 'Install the official Arch limine package first'; return 1; }
 [[ ! -L /run/titan-boot.lock ]] || { titan_boot_fail 'Boot lock must not be a symlink'; return 1; }
 exec 9>/run/titan-boot.lock
 flock -n 9 || { titan_boot_fail 'Another boot refresh is running'; return 1; }
 for path in "$config" "$config.previous" "$binary" "$binary.previous"; do titan_boot_path "$path" || return; done
 if [[ -e $config ]]; then
  local first; IFS= read -r first <"$config"
  [[ $first == "$titan_boot_marker" ]] || { titan_boot_fail 'Refusing to replace an unmanaged Limine configuration'; return 1; }
 fi
 # Render and stage before replacing anything. Keep staging on the ESP so
 # rename is atomic; preserve the previous version of each changed file.
 stage=$(mktemp -d /boot/.titan-boot.XXXXXX)
 titan_boot_stage=$stage
 trap 'rm -rf -- "$titan_boot_stage"' EXIT
 titan_boot_render "$uuid" /boot /etc/titan/limine.conf >"$stage/menu" || return
 cp -- "$source" "$stage/firmware"
 mkdir -p -- "${binary%/*}"
 local destination input
 for destination in "$binary" "$config"; do
  if [[ $destination == "$binary" ]]; then input=$stage/firmware; else input=$stage/menu; fi
  if [[ -f $destination ]]; then
   cmp -s -- "$destination" "$input" && continue
   cp -- "$destination" "$stage/previous"
   mv -f -- "$stage/previous" "$destination.previous"
  fi
  sync -f "$input"
  mv -f -- "$input" "$destination"
 done
 sync -f /boot
 echo 'Limine refreshed; previous changed files retained beside outputs.'
}

source "$(dirname -- "${BASH_SOURCE[0]}")/snapshots.sh"
