font_family JetBrains Mono
font_size 11
background #080a0d
foreground #dce0e5
selection_background #353b44
selection_foreground #ffffff
cursor #c4cbd4
cursor_shape beam
window_padding_width 18
hide_window_decorations yes
background_opacity 0.92
confirm_os_window_close 0
enable_audio_bell no
linux_display_server wayland
color0 #15171b
color1 #bd8585
color2 #a4b5a1
color3 #bbb29a
color4 #96a6bb
color5 #aea0b8
color6 #9bb5b5
color7 #cdd1d7
color8 #555d68
color9 #cd9595
color10 #b4c5b1
color11 #cbc2aa
color12 #a6b6cb
color13 #beb0c8
color14 #abc5c5
color15 #edf0f4
